from . import loan_car_report_wiz
from . import total_tanker_wiz
from . import garbage_report_wiz
from . import compare_garbage_wiz
from . import compare_sanitation_wiz
from . import car_move_wiz
from . import total_car_move
from . import inventory_scrap_wiz
from . import car_att_excel_report
from . import ledger_report
